receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  resource:
    attributes:
      - action: upsert
        key: service.name
        value: central-logging-app
  batch: {}

exporters:
  loki:
    endpoint: https://logs-prod-<region>.grafana.net/loki/api/v1/push
    auth:
      authenticator: basicauth/client
    default_labels_enabled:
      exporter: false
      job: false
      instance: false
    labels:
      resource:
        - service.name
        - service.namespace
        - service.instance.id
        - service.version
      attributes:
        - logger.name
        - severity
        - log.file.name
        - code.function
        - code.lineno

extensions:
  basicauth/client:
    client_auth:
      username: ${env:GRAFANA_CLOUD_STACK_ID}
      password: ${env:GRAFANA_CLOUD_API_KEY}

service:
  extensions: [basicauth/client]
  pipelines:
    logs:
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [loki]
