receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  resource:
    attributes:
      - action: upsert
        key: service.name
        value: central-logging-system
  batch: {}

exporters:
  otlphttp/grafanaCloudOTLP:
    endpoint: https://otlp-gateway-prod-gb-south-1.grafana.net/otlp
    auth:
      authenticator: basicauth/grafanaCloud

extensions:
  basicauth/grafanaCloud:
    client_auth:
      username: ${env:GRAFANA_CLOUD_STACK_ID}
      password: ${env:GRAFANA_CLOUD_API_KEY}

service:
  extensions: [basicauth/grafanaCloud]
  pipelines:
    logs:
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [otlphttp/grafanaCloudOTLP]
